apiVersion: v1
kind: Service
metadata:
  name: myweb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: myweb
  ports:
  - port: 80
    targetPort: 8080
